name: Bug Report
description: Report an issue.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
  - type: checkboxes
    attributes:
      options:
        - label: I've confirmed that I am completely up-to-date.
          required: true
  - type: checkboxes
    attributes:
      options:
        - label: I've verified that the problem persists in the Experimental Branch.
          required: true
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser were you using?
      placeholder: (Example > Google Chrome, Edge, Firefox, Opera)
    validations:
      required: true
  - type: input
    id: page-url
    attributes:
      label: Page URL
      placeholder: (Example > https://www.roblox.com/home)
    validations:
      required: false
  - type: dropdown
    id: channel
    attributes:
      label: Channel
      description: The channel you were on when it occured.
      options:
        - Release
        - Experimental
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - CSS
        - JavaScript
        - Both
    validations:
      required: true
  - type: textarea
    id: describe-issue
    attributes:
      label: Describe the Problem
      description: Describe the issue you're facing. ([Optional] Provide a screenshot or a video that recreates the bug.)
    validations:
      required: true