name: Bug Report
description: Report an issue.
labels: [bug]
body:
  - type: markdown
    attributes:
      value: |
        # Bug Report
        Before you begin make sure you're fully up to date before you start filling out the form.
  - type: input
    id: browser
    attributes:
      label: Browser
      description: What browser were you using?
      placeholder: Example > Google Chrome
    validations:
      required: true
  - type: input
    id: page-url
    attributes:
      label: Page URL
      placeholder: Example > https://www.roblox.com/home
    validations:
      required: false
  - type: dropdown
    id: channel
    attributes:
      label: Channel
      description: The channel you were on when it occured.
      options:
        - Release
        - Experimental
    validations:
      required: true
  - type: dropdown
    id: type
    attributes:
      label: Type
      options:
        - CSS
        - JavaScript
        - Both
    validations:
      required: true
  - type: textarea
    id: describe-issue
    attributes:
      label: Describe the Problem
      description: Describe the issue you're facing. Please provide a screenshot or a video into recreating the problem.
    validations:
      required: true